[package]
name = "talpid-firewall"
description = "Privacy preserving and secure firewall library"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
ipnetwork = { workspace = true }
libc = "0.2"
log = { workspace = true }
talpid-tunnel = { path = "../talpid-tunnel" }
talpid-types = { path = "../talpid-types" }
talpid-wireguard = { path = "../talpid-wireguard" }

[target.'cfg(not(target_os = "android"))'.dependencies]
talpid-dns = { path = "../talpid-dns" }

[target.'cfg(target_os = "linux")'.dependencies]
nftnl = { version = "0.8.0", features = ["nftnl-1-1-0"] }
mnl = { version = "0.2.3", features = ["mnl-1-0-4"] }
talpid-net = { path = "../talpid-net" }
talpid-split-tunnel = { path = "../talpid-split-tunnel" }

[target.'cfg(target_os = "macos")'.dependencies]
pfctl = "0.7.0"
talpid-platform-metadata = { path = "../talpid-platform-metadata" }

[target.'cfg(windows)'.dependencies]
widestring = { workspace = true }
winreg = { workspace = true, features = ["transactions"] }
talpid-windows = { path = "../talpid-windows" }
tokio = { workspace = true, features = ["process", "rt-multi-thread", "fs"] }

wmi = "0.14.0"
windows-core = "0.58.0"
windows = "0.58.0"

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Ioctl",
    "Win32_System_IO",
    "Win32_System_LibraryLoader",
    "Win32_System_ProcessStatus",
    "Win32_System_Registry",
    "Win32_System_Rpc",
    "Win32_System_Services",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_SystemInformation",
]
