[package]
name = "talpid-cgroup"
description = "An abstraction for linux cgroup"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
anyhow.workspace = true
nix = { workspace = true, features = ["fs", "mount"] }
libc = "0.2"
log.workspace = true
thiserror.workspace = true
talpid-types.path = "../talpid-types"
