[package]
name = "talpid-cgroup"
edition.workspace = true
rust-version.workspace = true
description = "An abstraction for linux cgroup"
repository.workspace = true
license.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
anyhow.workspace = true
log.workspace = true
nix = { workspace = true, features = ["fs", "mount", "process"] }
thiserror.workspace = true

[lints]
workspace = true
