[package]
name = "mullvad-tests"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>", "Janito Vaqueiro Ferreira Filho <janito@mullvad.net>"]
description = "Mullvad test specific modules and binaries"
license = "GPL-3.0"

[features]
integration-tests = []

[dependencies]
duct = "0.11"
mullvad-ipc-client = { path = "../mullvad-ipc-client" }
mullvad-paths = { path = "../mullvad-paths" }
mullvad-types = { path = "../mullvad-types" }
notify = "4.0"
openvpn-plugin = { version = "0.3", features = ["serde"] }
talpid-ipc = { path = "../talpid-ipc" }
tempfile = "3.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
