[package]
name = "mullvad-paths"
version = "0.1.0"
authors = ["Mullvad VPN"]
description = "Mullvad VPN application paths and directories"
license = "GPL-3.0"
edition = "2018"
publish = false

[dependencies]
err-derive = "0.2.1"
log = "0.4"

[target.'cfg(any(windows, target_os = "macos"))'.dependencies]
dirs = "3.0"
