[package]
name = "talpid-net"
edition.workspace = true
rust-version.workspace = true
description = "Networking helpers"
repository.workspace = true
license.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"
log = { workspace = true }
nix = { workspace = true, features = ["net"] }
socket2 = { workspace = true, features = ["all"] }
talpid-types = { path = "../talpid-types" }
thiserror = { workspace = true }

[lints]
workspace = true
