[package]
name = "talpid-relay-config-client"
version = "0.1.0"
authors = ["Mullvad VPN"]
description = "Uses relays to set up PQ-safe peers, etc."
license = "GPL-3.0"
edition = "2021"
publish = false

[dependencies]
log = "0.4"
rand = "0.8"
talpid-types = { path = "../talpid-types" }
tonic = "0.5"
prost = "0.8"
prost-types = "0.9"
tower = "0.4"
tokio = { version = "1", features = ["rt-multi-thread"] }
classic-mceliece-rust = { version = "1.0", features = ["mceliece8192128f"] }

[build-dependencies]
tonic-build = { version = "0.5", default-features = false, features = ["transport", "prost"] }