[package]
name = "tunnel-obfuscator-proxy"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[lib]
crate-type = [ "rlib", "staticlib" ]
bench = false

[target.'cfg(target_os = "ios")'.dependencies]
tunnel-obfuscation = { path = "../../../tunnel-obfuscation" }
tokio = { workspace = true, features = ["sync"] }
log = "0.4"
oslog = "0.2"

[target.'cfg(target_os = "ios")'.build-dependencies]
cbindgen = { version = "0.24.3", default-features = false }
