sudo: false

git:
  submodules: false

before_install:
  - git submodule update --init

matrix:
  include:
    # GUI - components
    - language: node_js
      node_js: '8'
      cache: yarn
      env:
        - WORKSPACE="@mullvad/components"
      install: &nodejs_install_script
        - cd gui
        - yarn install
      before_script: &nodejs_before_script
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
      script:
        - yarn workspace $WORKSPACE lint
        - yarn workspace $WORKSPACE build
        - yarn workspace $WORKSPACE test

    # GUI - desktop
    - language: node_js
      node_js: '8'
      cache: yarn
      env:
        - WORKSPACE="desktop"
      install: *nodejs_install_script
      before_script: *nodejs_before_script
      script:
        - yarn check-format
        - yarn workspace $WORKSPACE lint
        - yarn workspace $WORKSPACE build
        - yarn workspace $WORKSPACE test


    # Daemon - macOS
    - language: rust
      rust: stable
      os: osx
      cache: cargo
      before_script: &rust_before_script
        - source env.sh
        - env
        - du -sh target || true
      script: &rust_script
        - cargo build --verbose
        - cargo test --verbose
      before_cache: &rust_before_cache
        - rm -rf target/debug/incremental/

    # Daemon - Linux
    - language: rust
      rust: nightly
      os: linux
      addons: &rust_linux_addons
        apt:
         sources:
          - sourceline: "ppa:jonathonf/gcc-7.3"
            key_url: "https://pgp.key-server.io/download/0xE03043828C3FF4BB"
         packages:
          - binutils
          - libdbus-1-dev
      cache: cargo
      before_script: *rust_before_script
      script:
        - cargo build --verbose
        - cargo test --verbose
        # Install and run rustfmt on nightly only until rustfmt.toml settings are stabilized.
        - rustup component add rustfmt-preview
        - cargo fmt --version || true
        - cargo fmt -- --check --unstable-features
      before_cache: *rust_before_cache

    - language: rust
      rust: beta
      os: linux
      addons: *rust_linux_addons
      cache: cargo
      before_script: *rust_before_script
      script: *rust_script
      before_cache: *rust_before_cache

    - language: rust
      rust: stable
      os: linux
      addons: *rust_linux_addons
      cache: cargo
      before_script: *rust_before_script
      script: *rust_script
      before_cache: *rust_before_cache


notifications:
  email:
    on_success: never
    on_failure: never
