sudo: false

git:
  submodules: false

before_install:
  - git submodule update --init

matrix:
  include:
    # GUI - Electron
    - language: node_js
      node_js: '8'
      cache: npm
      install:
        - cd gui
        - npm install
      before_script:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
      script:
        - npm run check-format
        - npm run lint
        - npm run build
        - npm test

    # Android
    - language: android
      sudo: true
      android:
        components:
          - android-28
          - build-tools-28.0.3
      install:
        - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
        - source $HOME/.cargo/env
        - rustup target add aarch64-linux-android
        - curl -sf -L -o /tmp/ndk.zip https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip
        - sudo mkdir /opt/android
        - sudo unzip -q -d /opt/android/ /tmp/ndk.zip
        - sudo /opt/android/android-ndk-r20/build/tools/make-standalone-toolchain.sh --platform=android-21 --arch=arm64 --install-dir=/opt/android/toolchains/android21-aarch64
        - |
            cat >> $HOME/.cargo/config << EOF
            [target.aarch64-linux-android]
            ar = "/opt/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar"
            linker = "/opt/android/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang"
      before_script:
        - export RUSTFLAGS="--deny unused_imports --deny dead_code"
        - export AR_aarch64_linux_android=/opt/android/toolchains/android21-aarch64/bin/aarch64-linux-android-ar
        - export CC_aarch64_linux_android=/opt/android/toolchains/android21-aarch64/bin/aarch64-linux-android21-clang
        - source env.sh aarch64-linux-android
        - env
      script:
        - cargo build --target aarch64-linux-android --verbose
        - cd android
        - ./gradlew --console plain assembleDebug

    # Daemon - macOS
    - language: rust
      rust: stable
      os: osx
      before_script:
        - env
      script:
        - ./ci/travis-rust-script.sh stable

    # Daemon - Linux
    - os: linux
      name: Daemon - nigtly Rust
      language: minimal
      dist: xenial
      services: docker
      before_script: &rust_before_script
        - docker run -d --name mvd-build -v $(pwd):/travis -w /travis  mullvadvpn/mullvadvpn-app-build:latest tail -f /dev/null
        - docker ps
      script:
        - docker exec -t mvd-build bash ci/travis-rust-script.sh nightly

    - os: linux
      name: Daemon - beta Rust
      language: minimal
      dist: xenial
      services: docker
      before_script: *rust_before_script
      script:
        - docker exec -t mvd-build bash ci/travis-rust-script.sh beta

    - os: linux
      name: Daemon - stable Rust
      language: minimal
      dist: xenial
      services: docker
      before_script: *rust_before_script
      script:
        - docker exec -t mvd-build bash ci/travis-rust-script.sh stable


notifications:
  email:
    on_success: never
    on_failure: never
