# Activation of features, almost objectively better ;)
reorder_imports = true
reorder_imports_in_group = true
use_try_shorthand = true
condense_wildcard_suffices = true
normalize_comments = true
wrap_comments = true

# Heavily subjective style choices
comment_width = 100
chain_one_line_max = 100
