[package]
name = "mullvad-api-constants"
edition.workspace = true
rust-version.workspace = true
description = "Mullvad VPN API client constants"
repository.workspace = true
license.workspace = true

[lints]
workspace = true
