[package]
name = "mullvad-types"
description = "Common base data structures for Mullvad VPN client"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
chrono = { workspace = true, features = ["clock", "serde"] }
err-derive = "0.3.1"
ipnetwork = "0.16"
once_cell = "1.13"
log = "0.4"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
uuid = { version = "1.4.1", features = ["v4", "serde" ] }

talpid-types = { path = "../talpid-types" }

clap = { version = "4.2.7", features = ["derive"], optional = true }

[target.'cfg(target_os = "android")'.dependencies]
jnix = { version = "0.5", features = ["derive"] }
