[package]
name = "mullvad-types"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>", "Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>", "Andrej Mihajlov <and@mullvad.net>"]
description = "Common base data structures for Mullvad VPN client"
license = "GPL-3.0"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde_derive = "1.0"
serde = "1.0"
error-chain = "0.11"
log = "0.3"

talpid-types = { path = "../talpid-types" }
