[package]
name = "mullvad-types"
version = "0.0.0"
authors = ["Mullvad VPN"]
description = "Common base data structures for Mullvad VPN client"
license = "GPL-3.0"
edition = "2021"
publish = false

[dependencies]
chrono = { version = "0.4.21", features = ["serde"] }
err-derive = "0.3.1"
ipnetwork = "0.16"
lazy_static = "1.1.0"
log = "0.4"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"

talpid-types = { path = "../talpid-types" }

[target.'cfg(target_os = "android")'.dependencies]
jnix = { version = "0.5", features = ["derive"] }
