[package]
name = "mullvad-types"
description = "Common base data structures for Mullvad VPN client"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
chrono = { workspace = true, features = ["clock", "serde"] }
thiserror = { workspace = true }
ipnetwork = "0.16"
once_cell = { workspace = true }
log = { workspace = true }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.4.1", features = ["v4", "serde" ] }

talpid-types = { path = "../talpid-types" }

clap = { workspace = true , optional = true }

[target.'cfg(target_os = "android")'.dependencies]
jnix = { version = "0.5.1", features = ["derive"] }

[dev-dependencies]
proptest = "1.4"
