[package]
name = "mullvad-types"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>"]
description = "Common base data structures for Mullvad VPN client"
license = "GPL-3.0"
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
err-derive = "0.1.5"
ipnetwork = "0.15"
lazy_static = "1.1.0"
log = "0.4"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

talpid-types = { path = "../talpid-types" }
mullvad-paths = { path = "../mullvad-paths" }
