[package]
name = "talpid-split-tunnel"
description = "Privacy-destroying VPN circumvention library"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
talpid-types = { path = "../talpid-types" }
tokio = { workspace = true, features = ["process", "rt-multi-thread", "fs"] }

[target.'cfg(target_os = "android")'.dependencies]
talpid-tunnel = { path = "../talpid-tunnel" }

[target.'cfg(target_os = "linux")'.dependencies]
nix = { workspace = true, features = ["mount"] }

[target.'cfg(target_os = "macos")'.dependencies]
talpid-platform-metadata = { path = "../talpid-platform-metadata" }
pcap = { version = "2.1", features = ["capture-stream"] }
pnet_packet = { workspace = true }
tun = { workspace = true, features = ["async"] }
libc = "0.2"
nix = { workspace = true, features = ["socket", "signal", "user"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
talpid-macos = { path = "../talpid-macos" }
talpid-routing = { path = "../talpid-routing" }
talpid-net = { path = "../talpid-net" }
either = { version = "1.15.0", features = ["serde"] }

[target.'cfg(windows)'.dependencies]
bitflags = "2.6"
memoffset = "0.6"
windows-service = "0.6.0"
talpid-routing = { path = "../talpid-routing" }
talpid-windows = { path = "../talpid-windows" }

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Ioctl",
    "Win32_System_IO",
    "Win32_System_LibraryLoader",
    "Win32_System_ProcessStatus",
    "Win32_System_Registry",
    "Win32_System_Rpc",
    "Win32_System_Services",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_SystemInformation",
]

[dev-dependencies]
tokio = { workspace = true, features = ["io-util", "test-util", "time"] }
insta = { workspace = true }
