[package]
name = "mullvad-api"
version = "0.0.0"
authors = ["Mullvad VPN"]
description = "Mullvad VPN API clients. Providing an interface to query our infrastructure for information."
license = "GPL-3.0"
edition = "2021"
publish = false

[features]
# Allow the API server to use to be configured via MULLVAD_API_HOST and MULLVAD_API_ADDR.
api-override = []

[dependencies]
chrono = { version = "0.4.21", features = ["serde"] }
err-derive = "0.3.1"
futures = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["client", "stream", "http1", "tcp" ] }
ipnetwork = "0.16"
log = "0.4"
regex = "1"
serde = "1"
serde_json = "1.0"
tokio = { version = "1.8", features = ["macros", "time", "rt-multi-thread", "net", "io-std", "io-util", "fs"] }
tokio-rustls = "0.23"
rustls-pemfile = "0.2"
once_cell = "1.13"

mullvad-types = { path = "../mullvad-types" }
talpid-types = { path = "../talpid-types" }
talpid-time = { path = "../talpid-time" }

shadowsocks = { version = "1.14.2", default-features = false, features = ["stream-cipher"] }

uuid = { version = "0.8", features = ["v4"] }
