[package]
name = "nullvad"
version = "0.0.0"
edition = "2024"

[[bin]]
name = "nullvad-exec"
path = "src/bin/nullvad_exec.rs"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
env_logger.workspace = true
futures.workspace = true
log.workspace = true
nix = { workspace = true, features = ["sched", "socket", "uio", "user", "fs", "mount"] }
rtnetlink.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["rt"] }
zerocopy = { workspace = true, features = ["std", "derive"] }

mnl = "0.2.3"
netlink-packet = "0.1.1"
netlink-packet-core = "0.8.1"
netlink-packet-route = "0.25.1"

nftnl = { path = "../../nftnl-rs/nftnl" }
