[package]
name = "talpid-tunnel-config-client"
version = "0.0.0"
authors = ["Mullvad VPN"]
description = "Uses the relay RPC service to set up PQ-safe peers, etc."
license = "GPL-3.0"
edition = "2021"
publish = false

[dependencies]
log = "0.4"
rand = "0.8"
talpid-types = { path = "../talpid-types" }
tonic = "0.8"
prost = "0.11"
tower = "0.4"
tokio = "1"
classic-mceliece-rust = { version = "2.0.0", features = ["mceliece460896f", "zeroize"] }
pqc_kyber = { version = "0.4.0", features = ["std", "kyber1024", "zeroize"] }
zeroize = "1.5.7"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }

[build-dependencies]
tonic-build = { version = "0.8", default-features = false, features = ["transport", "prost"] }
