[package]
name = "talpid-tunnel-config-client"
description = "Uses the relay RPC service to set up PQ-safe peers, etc."
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
log = { workspace = true }
rand = "0.8"
talpid-types = { path = "../talpid-types" }
tonic = { workspace = true }
tower = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
classic-mceliece-rust = { version = "2.0.0", features = ["mceliece460896f", "zeroize"] }
pqc_kyber = { version = "0.4.0", features = ["std", "kyber1024", "zeroize"] }
zeroize = "1.5.7"
libc = "0.2"

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
    "Win32_Networking_WinSock"
]

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }

[build-dependencies]
tonic-build = { workspace = true, default-features = false, features = ["transport", "prost"] }
