[package]
name = "talpid_cli"
version = "0.0.0"
authors = ["Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>"]
description = "Run Talpid easily from the command line"

[dependencies]
clap = "2.20"
error-chain = "0.8"

[dependencies.talpid_core]
path = "../"
