[package]
name = "translations-converter"
description = "Converts between PO and Android style localization formats"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
htmlize = { version = "1.0.2", features = ["unescape"] }
regex = "1"
serde = { workspace = true, features = ["derive"] }
quick-xml = { version = "0.27.1", features = ["serialize"] }
itertools = "0.14.0"
