[package]
name = "translations-converter"
version = "0.1.0"
authors = ["Mullvad VPN"]
license = "GPL-3.0"
edition = "2021"
publish = false

[dependencies]
derive_more = "0.99"
htmlize = "0.5"
lazy_static = "1"
regex = "1"
serde = { version = "1", features = ["derive"] }
quick-xml = { version = "0.27.1", features = ["serialize"] }
