[package]
name = "translations-converter"
version = "0.1.0"
authors = ["Mullvad VPN"]
license = "GPL-3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99"
htmlize = "0.5"
lazy_static = "1"
regex = "1"
roxmltree = "0.14"
serde = { version = "1", features = ["derive"] }
serde-xml-rs = "0.4"
