[package]
name = "talpid-dns"
description = "Privacy preserving and secure DNS client library"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
log = { workspace = true }
parking_lot = "0.12.0"
talpid-routing = { path = "../talpid-routing" }
talpid-types = { path = "../talpid-types" }
tokio = { workspace = true, features = ["macros"] }

[target.'cfg(target_os="linux")'.dependencies]
triggered = "0.1.1"
futures = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
nix = { workspace = true, features = ["mount", "net"] }
inotify = "0.10"
resolv-conf = "0.7"
which = { version = "4.0", default-features = false }
talpid-dbus = { path = "../talpid-dbus" }

[target.'cfg(target_os = "macos")'.dependencies]
system-configuration = "0.5.1"
hickory-proto = { workspace = true }
hickory-server = { workspace = true, features = ["resolver"] }

[target.'cfg(windows)'.dependencies]
widestring = { workspace = true }
winreg = { workspace = true, features = ["transactions"] }
once_cell = { workspace = true }
talpid-windows = { path = "../talpid-windows" }

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Ioctl",
    "Win32_System_IO",
    "Win32_System_LibraryLoader",
    "Win32_System_ProcessStatus",
    "Win32_System_Registry",
    "Win32_System_Rpc",
    "Win32_System_Services",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_SystemInformation",
]
