[package]
name = "talpid-dns"
description = "Privacy preserving and secure DNS library"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
log = { workspace = true }
talpid-types = { path = "../talpid-types" }

[target.'cfg(target_os = "linux")'.dependencies]
futures = { workspace = true }
inotify = "0.10"
nix = { workspace = true, features = ["net"] }
parking_lot = "0.12.0"
resolv-conf = "0.7"
talpid-dbus = { path = "../talpid-dbus" }
talpid-routing = { path = "../talpid-routing" }
tokio = { workspace = true, features = ["macros"] }
triggered = "0.1.1"
which = { version = "4.0", default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
parking_lot = "0.12.0"
system-configuration = "0.5.1"
talpid-routing = { path = "../talpid-routing" }

[target.'cfg(windows)'.dependencies]
once_cell = { workspace = true }
talpid-windows = { path = "../talpid-windows" }
winreg = { workspace = true, features = ["transactions"] }

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Ioctl",
    "Win32_System_IO",
    "Win32_System_LibraryLoader",
    "Win32_System_ProcessStatus",
    "Win32_System_Registry",
    "Win32_System_Rpc",
    "Win32_System_Services",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_SystemInformation",
]
