[package]
name = "talpid-routing"
edition.workspace = true
rust-version.workspace = true
description = "Library for managing routing tables"
repository.workspace = true
license.workspace = true

[dependencies]
futures = { workspace = true }
ipnetwork = { workspace = true }
log = { workspace = true }
talpid-types = { path = "../talpid-types" }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
  "io-util",
  "net",
  "process",
  "rt-multi-thread",
  "time"
] }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }

[target.'cfg(target_os = "android")'.dependencies]
jnix = { version = "0.5.2", features = ["derive"] }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
netlink-packet-core = { workspace = true }
netlink-packet-route = { workspace = true, features = ["rich_nlas"] }
netlink-sys = { workspace = true }
rtnetlink = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
bitflags = "2"
libc = "0.2"
nix = { workspace = true, features = ["fs", "net", "socket"] }
system-configuration = "0.5.1"

[target.'cfg(windows)'.dependencies]
talpid-windows = { path = "../talpid-windows" }
widestring = { workspace = true }

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = ["Win32_Globalization", "Win32_NetworkManagement_Ndis"]

[lints]
workspace = true
