[package]
name = "talpid-routing"
description = "Library for managing routing tables"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
futures = { workspace = true }
ipnetwork = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = ["process", "rt-multi-thread", "net", "io-util", "time"] }
talpid-types = { path = "../talpid-types" }

[target.'cfg(target_os = "android")'.dependencies]
jnix = { version = "0.5.2", features = ["derive"] }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
rtnetlink = "0.11"
netlink-packet-route = { version = "0.13", features = ["rich_nlas"] }
netlink-sys = "0.8.3"

[target.'cfg(target_os = "macos")'.dependencies]
nix = { version = "0.28", features = ["socket", "fs", "net"] }
libc = "0.2"
bitflags = "2"
system-configuration = "0.5.1"


[target.'cfg(windows)'.dependencies]
talpid-windows = { path = "../talpid-windows" }
widestring = "1.0"

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
    "Win32_NetworkManagement_Ndis",
    "Win32_Globalization"
]

[dev-dependencies]
tokio = { workspace = true, features = [ "test-util" ] }
