[package]
name = "mullvad-nsis"
description = "Helper library used by Mullvad NSIS plugins"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
crate_type = ["staticlib"]

[target.i686-pc-windows-msvc.dependencies]
mullvad-paths = { path = "../mullvad-paths" }

[target.i686-pc-windows-msvc.build-dependencies]
cbindgen = { version = "0.24.3", default-features = false }