[package]
name = "mullvad-nsis"
description = "Helper library used by Mullvad NSIS plugins"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["staticlib"]

[target.i686-pc-windows-msvc.dependencies]
mullvad-paths = { path = "../mullvad-paths" }
talpid-platform-metadata = { path = "../talpid-platform-metadata" }
windows-sys = { workspace = true, features = [
    "Wdk_Foundation",
    "Wdk_System",
    "Wdk_System_SystemInformation",
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_Storage_FileSystem",
    "Win32_Security",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
] }
libloading = { version = "0.9.0" }

[target.'cfg(target_os = "windows")'.build-dependencies]
cbindgen = { version = "0.28.0", default-features = false }
