[package]
name = "mullvad-update"
edition.workspace = true
rust-version.workspace = true
description = "Support functions for securely installing or updating Mullvad VPN"
repository.workspace = true
license.workspace = true

[[bin]]
name = "mullvad-version-metadata"
required-features = ["sign"]

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true, features = ["now", "serde"] }
clap = { workspace = true, optional = true }
ed25519-dalek = { version = "2.1", features = ["rand_core", "zeroize"] }
hex = { version = "0.4" }
itertools = { workspace = true }
json-canon = "0.1"
log = { workspace = true }
mullvad-api-constants = { path = "../mullvad-api/mullvad-api-constants" }
mullvad-version = { path = "../mullvad-version", features = ["serde"] }
# If a consumer enable the `proptest` feature, then we expose proptest generators in the public API
proptest = { workspace = true, optional = true }
rand = { workspace = true }
# TODO Upgrading to rand 0.9 is blocked on ed25519-dalek dropping their dependency on rand_core 0.6
# (as of ed25519-dalek 2.2.0)
rand08 = { package = "rand", version = "0.8.5", optional = true }
reqwest = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
strum = { workspace = true, features = ["derive"], optional = true }
thiserror = { workspace = true, optional = true }
tokio = { workspace = true, features = [
  "fs",
  "macros",
  "process",
  "rt-multi-thread"
], optional = true }
vec1 = { workspace = true }
zeroize = { version = "1.8", features = ["zeroize_derive"] }

[dev-dependencies]
async-tempfile = "0.6"
insta = { workspace = true }
mockito = "1.6.1"
proptest = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "test-util", "time"] }

[features]
default = []
client = ["reqwest", "thiserror", "tokio"]
sign = ["clap", "rand08"]

[lints]
workspace = true
