[package]
name = "mullvad-update"
description = "Support functions for securely installing or updating Mullvad VPN"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []
sign = ["rand", "clap"]
client = ["reqwest", "sha2", "tokio", "thiserror"]

[dependencies]
anyhow = { workspace = true }
json-canon = "0.1"
chrono = { workspace = true, features = ["serde", "now"] }
ed25519-dalek = { version = "2.1", features = ["zeroize", "rand_core"] }
hex = { version = "0.4" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
zeroize = { version = "1.8", features = ["zeroize_derive"] }

reqwest = { version = "0.12.9", default-features = false, features = ["rustls-tls"], optional = true }
sha2 = { version = "0.10", optional = true }
tokio = { workspace = true, features = ["rt-multi-thread", "fs", "process", "macros"], optional = true }
vec1 = { workspace = true }

mullvad-version = { path = "../mullvad-version", features = ["serde"] }

# features required by binaries
clap = { workspace = true, optional = true }
rand = { version = "0.8.5", optional = true }

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
thiserror = { workspace = true, optional = true }

[dev-dependencies]
async-tempfile = "0.6"
insta = { workspace = true }
mockito = "1.6.1"
rand = "0.8.5"
tokio = { workspace = true, features = ["fs", "test-util", "time", "macros"] }

[[bin]]
name = "mullvad-version-metadata"
required-features = ["sign"]
