[package]
name = "talpid-types"
description = "Common base structures for talpid"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ipnetwork = "0.16"
base64 = "0.13"
x25519-dalek = { version = "2.0.1", features = ["static_secrets", "zeroize", "getrandom"] }
thiserror = { workspace = true }
zeroize = "1.5.7"
log = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
jnix = { version = "0.5.1", features = ["derive"] }
