[package]
name = "talpid-types"
edition.workspace = true
rust-version.workspace = true
description = "Common base structures for talpid"
repository.workspace = true
license.workspace = true

[dependencies]
base64 = "0.22.0"
ipnetwork = { workspace = true, features = ["serde"] }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
x25519-dalek = { version = "2.0.1", features = [
  "getrandom",
  "static_secrets",
  "zeroize"
] }
zeroize = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
jnix = { version = "0.5.1", features = ["derive"] }

[lints]
workspace = true
