[package]
name = "talpid-types"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>"]
description = "Common base structures for talpid"
license = "GPL-3.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ipnetwork = "0.14"
base64 = "0.10"
hex = "0.3"
error-chain = "0.12"
