[package]
name = "talpid-core"
version = "0.1.0"
authors = ["Mullvad VPN"]
description = "Privacy preserving and secure VPN client library"
license = "GPL-3.0"
edition = "2021"
publish = false

[dependencies]
bitflags = "1.2"
async-trait = "0.1"
atty = "0.2"
cfg-if = "1.0"
duct = "0.13"
err-derive = "0.3.0"
futures = "0.3.15"
hex = "0.4"
ipnetwork = "0.16"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
os_pipe = "0.9"
parking_lot = "0.11"
regex = "1.1.0"
shell-escape = "0.1"
talpid-types = { path = "../talpid-types" }
uuid = { version = "0.8", features = ["v4"] }
zeroize = "1"
chrono = "0.4.19"
tokio = { version = "1.8", features = [ "process", "rt-multi-thread", "fs" ] }
tokio-stream = { version = "0.1", features =  [ "io-util" ] }
rand = "0.7"
udp-over-tcp = { git = "https://github.com/mullvad/udp-over-tcp", rev = "1e27324362ed123b61fa2062b1599e5f9d569796" }
socket2 = { version = "0.4.2", features = [ "all" ] }

[target.'cfg(not(target_os="android"))'.dependencies]
parity-tokio-ipc = "0.9"
triggered = "0.1.1"
tonic = "0.5"
prost = "0.8"

[target.'cfg(unix)'.dependencies]
nix = "0.23"


[target.'cfg(target_os = "android")'.dependencies]
jnix = { version = "0.4", features = ["derive"] }


[target.'cfg(target_os = "linux")'.dependencies]
notify = "4.0"
resolv-conf = "0.7"
rtnetlink = "0.8"
netlink-packet-core = "0.2"
netlink-packet-utils = "0.4"
netlink-packet-route = "0.8"
netlink-proto = "0.7"
netlink-sys = "0.7"
byteorder = "1"
nftnl = { version = "0.6.2", features = ["nftnl-1-1-0"] }
mnl = { version = "0.2.2", features = ["mnl-1-0-4"] }
which = { version = "4.0", default-features = false }
tun = "0.5.1"
talpid-dbus = { path = "../talpid-dbus" }
internet-checksum = "0.2"


[target.'cfg(target_os = "macos")'.dependencies]
pfctl = "0.4.4"
system-configuration = "0.5"
trust-dns-server = {  git = "https://github.com/BlueJekyll/trust-dns", rev = "550e8f8be33df267b5c8e47586024cf17c3407f0",  features = [ "trust-dns-resolver" ] }
tun = "0.5.1"
subslice = "0.2"


[target.'cfg(windows)'.dependencies]
byteorder = "1"
internet-checksum = "0.2"
widestring = "0.5"
winreg = { version = "0.7", features = ["transactions"] }
winapi = { version = "0.3.6", features = ["combaseapi", "handleapi", "ifdef", "libloaderapi", "netioapi", "psapi", "stringapiset", "synchapi", "tlhelp32", "winbase", "winioctl", "winuser"] }
talpid-platform-metadata = { path = "../talpid-platform-metadata" }
memoffset = "0.6"

[build-dependencies]
tonic-build = { version = "0.5", default-features = false, features = ["transport", "prost"] }


[dev-dependencies]
tempfile = "3.0"
quickcheck = "1.0"
quickcheck_macros = "1.0"
