[package]
name = "talpid-core"
version = "0.0.0"
authors = ["Mullvad VPN"]
description = "Privacy preserving and secure VPN client library"
license = "GPL-3.0"
edition = "2021"
publish = false

[dependencies]
bitflags = "1.2"
async-trait = "0.1"
cfg-if = "1.0"
duct = "0.13"
err-derive = "0.3.1"
futures = "0.3.15"
hex = "0.4"
ipnetwork = "0.16"
lazy_static = "1.0"
once_cell = "1.13"
libc = "0.2"
log = "0.4"
os_pipe = "0.9"
parking_lot = "0.11"
regex = "1.1.0"
talpid-routing = { path = "../talpid-routing" }
talpid-types = { path = "../talpid-types" }
talpid-time = { path = "../talpid-time" }
talpid-tunnel-config-client = { path = "../talpid-tunnel-config-client" }
talpid-tunnel = { path = "../talpid-tunnel" }
talpid-wireguard = { path = "../talpid-wireguard" }
zeroize = "1"
chrono = "0.4.21"
tokio = { version = "1.8", features = ["process", "rt-multi-thread", "fs"] }
rand = "0.8.5"

[target.'cfg(not(target_os="android"))'.dependencies]
byteorder = "1"
internet-checksum = "0.2"
shadowsocks-service = { version = "1.14.3", default-features = false, features = ["local", "stream-cipher"] }
shell-escape = "0.1"
socket2 = { version = "0.4.2", features = ["all"] }
prost = "0.11"
parity-tokio-ipc = "0.9"
talpid-openvpn = { path = "../talpid-openvpn" }
triggered = "0.1.1"
tonic = "0.8"
uuid = { version = "0.8", features = ["v4"] }

[target.'cfg(unix)'.dependencies]
nix = "0.23"

[target.'cfg(target_os = "android")'.dependencies]
jnix = { version = "0.5", features = ["derive"] }

[target.'cfg(target_os = "linux")'.dependencies]
inotify = "0.10"
resolv-conf = "0.7"
rtnetlink = "0.11"
netlink-packet-route = "0.13"
netlink-sys = "0.8.3"
nftnl = { version = "0.6.2", features = ["nftnl-1-1-0"] }
mnl = { version = "0.2.2", features = ["mnl-1-0-4"] }
which = { version = "4.0", default-features = false }
tun = "0.5.1"
talpid-dbus = { path = "../talpid-dbus" }


[target.'cfg(target_os = "macos")'.dependencies]
pfctl = "0.4.4"
system-configuration = "0.5"
trust-dns-server = { version = "0.22.0", features = ["resolver"] }
tun = "0.5.1"
subslice = "0.2"


[target.'cfg(windows)'.dependencies]
widestring = "1.0"
winreg = { version = "0.7", features = ["transactions"] }
memoffset = "0.6"
windows-service = "0.5.0"
talpid-windows-net = { path = "../talpid-windows-net" }

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.42.0"
features = [
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Ioctl",
    "Win32_System_IO",
    "Win32_System_LibraryLoader",
    "Win32_System_ProcessStatus",
    "Win32_System_Registry",
    "Win32_System_Services",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
]

[build-dependencies]
tonic-build = { version = "0.8", default-features = false, features = ["transport", "prost"] }


[dev-dependencies]
tempfile = "3.0"
quickcheck = { version = "1.0", default-features = false }
quickcheck_macros = "1.0"
tokio = { version = "1", features = [ "test-util" ] }
