[package]
name = "talpid-core"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>"]
description = "Privacy preserving and secure VPN client library"
license = "GPL-3.0"

[dependencies]
atty = "0.2"
duct = "0.11"
error-chain = "0.12"
futures = "0.1"
jsonrpc-core = { git = "https://github.com/mullvad/jsonrpc", branch = "make-ipc-server-concurrent-part-deux" }
jsonrpc-macros = { git = "https://github.com/mullvad/jsonrpc", branch = "make-ipc-server-concurrent-part-deux" }

libc = "0.2.20"
log = "0.4"
openvpn-plugin = { git = "https://github.com/mullvad/openvpn-plugin-rs", branch = "auth-failed-event", features = ["serde"] }
os_pipe = "0.7"
shell-escape = "0.1"
tokio-core = "0.1"
uuid = { version = "0.6", features = ["v4"] }

talpid-ipc = { path = "../talpid-ipc" }
talpid-types = { path = "../talpid-types" }

[target.'cfg(unix)'.dependencies]
ipnetwork = "0.13"
lazy_static = "1.0"
tun = { git = "https://github.com/pinkisemils/rust-tun", branch = "add-raw-fd-traits" }
nix = "0.12"

[target.'cfg(target_os = "linux")'.dependencies]
dbus = "0.6"
failure = "0.1"
notify = "4.0"
resolv-conf = "0.6.1"
nftnl = { version = "0.1", features = ["nftnl-1-1-0"] }
mnl = { version = "0.1", features = ["mnl-1-0-4"] }
which = "2.0"

[target.'cfg(target_os = "macos")'.dependencies]
pfctl = "0.2"
system-configuration = "0.2"

[target.'cfg(windows)'.dependencies]
widestring = "0.3"
winreg = "0.5"
winapi = { version = "0.3.6", features = ["handleapi", "libloaderapi", "synchapi", "winbase", "winuser"] }

[dev-dependencies]
tempfile = "3.0"
