[package]
name = "talpid-core"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>"]
description = "Privacy preserving and secure VPN client library"
license = "GPL-3.0"
edition = "2018"

[dependencies]
atty = "0.2"
cfg-if = "0.1"
derive_more = "0.14"
duct = "0.12"
err-derive = "0.1.5"
futures = "0.1"
ipnetwork = "0.15"
jsonrpc-core = { git = "https://github.com/mullvad/jsonrpc", branch = "mullvad-fork" }
jsonrpc-macros = { git = "https://github.com/mullvad/jsonrpc", branch = "mullvad-fork" }
libc = "0.2.20"
log = "0.4"
openvpn-plugin = { git = "https://github.com/mullvad/openvpn-plugin-rs", branch = "auth-failed-event", features = ["serde"] }
os_pipe = "0.8"
parking_lot = "0.9"
regex = "1.1.0"
shell-escape = "0.1"
talpid-ipc = { path = "../talpid-ipc" }
talpid-types = { path = "../talpid-types" }
tokio-core = "0.1"
uuid = { version = "0.7", features = ["v4"] }


[target.'cfg(unix)'.dependencies]
hex = "0.4"
lazy_static = "1.0"
nix = "0.15"
tokio-process = "0.2"
tokio-executor = "0.1"
tokio-io = "0.1"


[target.'cfg(target_os = "linux")'.dependencies]
dbus = "0.6"
failure = "0.1"
notify = "4.0"
resolv-conf = "0.6.1"
rtnetlink = { git = "https://github.com/mullvad/netlink", rev = "f768adfcc8c6b064ef7ae3c792c4c21d0d96d0b5" }
netlink-proto = { git = "https://github.com/mullvad/netlink", rev = "f768adfcc8c6b064ef7ae3c792c4c21d0d96d0b5" }
netlink-packet = { git = "https://github.com/mullvad/netlink", rev = "f768adfcc8c6b064ef7ae3c792c4c21d0d96d0b5" }
netlink-sys = { git = "https://github.com/mullvad/netlink", rev = "f768adfcc8c6b064ef7ae3c792c4c21d0d96d0b5" }
nftnl = { version = "0.2.1", features = ["nftnl-1-1-0"] }
mnl = { version = "0.2.0", features = ["mnl-1-0-4"] }
which = "2.0"
tun = "0.4.3"


[target.'cfg(target_os = "macos")'.dependencies]
pfctl = "0.3"
system-configuration = "0.2"
tun = "0.4.3"


[target.'cfg(windows)'.dependencies]
widestring = "0.4"
winreg = "0.6"
winapi = { version = "0.3.6", features = ["handleapi", "libloaderapi", "synchapi", "winbase", "winuser"] }


[dev-dependencies]
tempfile = "3.0"
