[package]
name = "talpid-core"
edition.workspace = true
rust-version.workspace = true
description = "Privacy preserving and secure VPN client library"
repository.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
cfg-if = "1.0.4"
futures = { workspace = true }
ipnetwork = { workspace = true }
libc = "0.2"
log = { workspace = true }
rand = { workspace = true }
talpid-dns = { path = "../talpid-dns" }
talpid-routing = { path = "../talpid-routing" }
talpid-tunnel = { path = "../talpid-tunnel" }
talpid-types = { path = "../talpid-types" }
talpid-wireguard = { path = "../talpid-wireguard" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "process", "rt-multi-thread"] }

[dev-dependencies]
insta = { workspace = true }
serde_json.workspace = true
test-log = "0.2.17"
tokio = { workspace = true, features = ["io-util", "test-util", "time"] }

[target.'cfg(target_os = "android")'.dependencies]
jnix = { version = "0.5.1", features = ["derive"] }

[target.'cfg(target_os = "linux")'.dependencies]
mnl = { version = "0.3.1", features = ["mnl-1-0-4"] }
nftables = "0.6.3"
# NOTE: the libnftnl version specified in `features`
# MUST match the version we link in /.cargo/config.toml
nftnl = { version = "0.9.1", features = ["nftnl-1-2-0"] }
nix = { workspace = true, features = ["fs", "mount", "process"] }
talpid-cgroup = { path = "../talpid-cgroup" }
talpid-dbus = { path = "../talpid-dbus" }

[target.'cfg(target_os = "macos")'.dependencies]
async-trait = "0.1"
either = { version = "1.15.0", features = ["serde"] }
hickory-proto = { workspace = true }
hickory-server = { workspace = true, features = ["resolver"] }
nix = { workspace = true, features = ["signal", "socket", "user"] }
pcap = { version = "2.1", features = ["capture-stream"] }
pfctl = "0.7.0"
pnet_packet = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
socket2 = { workspace = true }
talpid-macos = { path = "../talpid-macos" }
talpid-net = { path = "../talpid-net" }
talpid-platform-metadata = { path = "../talpid-platform-metadata" }
tun = { workspace = true, features = ["async"] }

[target.'cfg(target_os = "macos")'.dev-dependencies]
typed-builder = "0.20.0"

[target.'cfg(windows)'.dependencies]
bitflags = "2.6"
chrono = { workspace = true, features = ["clock"] }
csv = "1.3.1"
memoffset = "0.6"
parking_lot = "0.12.0"
serde = { workspace = true, features = ["derive"] }
talpid-windows = { path = "../talpid-windows" }
widestring = { workspace = true }
windows = "0.58.0"
windows-core = "0.58.0"
windows-service = "0.6.0"
winreg = { workspace = true, features = ["transactions"] }
wmi = "0.14.0"

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
  "Win32_Foundation",
  "Win32_Globalization",
  "Win32_NetworkManagement_IpHelper",
  "Win32_NetworkManagement_Ndis",
  "Win32_Networking_WinSock",
  "Win32_Security",
  "Win32_Storage_FileSystem",
  "Win32_System_Diagnostics_ToolHelp",
  "Win32_System_IO",
  "Win32_System_Ioctl",
  "Win32_System_LibraryLoader",
  "Win32_System_ProcessStatus",
  "Win32_System_Registry",
  "Win32_System_Rpc",
  "Win32_System_Services",
  "Win32_System_SystemInformation",
  "Win32_System_SystemServices",
  "Win32_System_Threading",
  "Win32_System_WindowsProgramming",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
]

[features]
cgroup2 = []
multihop-pcap = ["talpid-wireguard/multihop-pcap"]
# nftables-json = ["dep:nftables"]
wireguard-go = ["talpid-wireguard/wireguard-go"]

[lints]
workspace = true
