[package]
name = "talpid-core"
version = "0.1.0"
authors = ["Mullvad VPN"]
description = "Privacy preserving and secure VPN client library"
license = "GPL-3.0"
edition = "2018"
publish = false

[dependencies]
atty = "0.2"
cfg-if = "0.1"
duct = "0.13"
err-derive = "0.2.1"
futures = { package = "futures", version = "0.3", features = [ "compat" ]}
hex = "0.4"
ipnetwork = "0.16"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
os_pipe = "0.9"
parking_lot = "0.11"
regex = "1.1.0"
shell-escape = "0.1"
talpid-types = { path = "../talpid-types" }
uuid = { version = "0.8", features = ["v4"] }
zeroize = "1"
chrono = "0.4"
tokio = { version = "0.2", features =  [ "process", "rt-threaded", "stream" ] }
rand = "0.7"
async-trait = "0.1.4"


[target.'cfg(not(target_os="android"))'.dependencies]
openvpn-plugin = { git = "https://github.com/mullvad/openvpn-plugin-rs", branch = "auth-failed-event", features = ["serde"] }
parity-tokio-ipc = "0.7"
triggered = "0.1.1"
tonic = "0.3.1"
prost = "0.6"

[target.'cfg(unix)'.dependencies]
nix = "0.18"


[target.'cfg(target_os = "android")'.dependencies]
jnix = { version = "0.2.3", features = ["derive"] }


[target.'cfg(target_os = "linux")'.dependencies]
dbus = "0.9"
failure = "0.1"
notify = "4.0"
resolv-conf = "0.6.1"
rtnetlink = "0.4"
netlink-packet-core = "0.2"
netlink-packet-utils = "0.2"
netlink-packet-route = "0.4"
netlink-proto = "0.4"
netlink-sys = "0.4"
byteorder = "1"
futures = { package = "futures", version = "0.3" }
nftnl = { version = "0.5", features = ["nftnl-1-1-0"] }
mnl = { version = "0.2.0", features = ["mnl-1-0-4"] }
which = { version = "4.0", default-features = false }
tun = "0.5"


[target.'cfg(target_os = "macos")'.dependencies]
pfctl = "0.4"
system-configuration = "0.4"
tun = "0.5"


[target.'cfg(windows)'.dependencies]
widestring = "0.4"
winreg = "0.7"
winapi = { version = "0.3.6", features = ["handleapi", "ifdef", "libloaderapi", "netioapi", "synchapi", "winbase", "winuser"] }
socket2 = "0.3"
pnet_packet = "0.26"

[build-dependencies]
tonic-build = { version = "0.3", default-features = false, features = ["transport", "prost"] }


[dev-dependencies]
tempfile = "3.0"
quickcheck = "0.9"
quickcheck_macros = "0.9"
