[package]
name = "talpid-core"
version = "0.1.0"
authors = ["Mullvad VPN"]
description = "Privacy preserving and secure VPN client library"
license = "GPL-3.0"
edition = "2018"
publish = false

[dependencies]
atty = "0.2"
cfg-if = "1.0"
duct = "0.13"
err-derive = "0.3.0"
futures = "0.3"
hex = "0.4"
ipnetwork = "0.16"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
os_pipe = "0.9"
parking_lot = "0.11"
regex = "1.1.0"
shell-escape = "0.1"
talpid-types = { path = "../talpid-types" }
uuid = { version = "0.8", features = ["v4"] }
zeroize = "1"
chrono = "0.4"
tokio = { version = "0.2", features =  [ "process", "rt-threaded", "stream" ] }
rand = "0.7"


[target.'cfg(not(target_os="android"))'.dependencies]
openvpn-plugin = { version = "0.4", features = ["serde", "auth-failed-event"] }
parity-tokio-ipc = "0.8"
triggered = "0.1.1"
tonic = "0.3.1"
prost = "0.6"

[target.'cfg(unix)'.dependencies]
nix = "0.19"


[target.'cfg(target_os = "android")'.dependencies]
jnix = { version = "0.4", features = ["derive"] }


[target.'cfg(target_os = "linux")'.dependencies]
failure = "0.1"
notify = "4.0"
resolv-conf = "0.7"
rtnetlink = "0.6"
netlink-packet-core = "0.2"
netlink-packet-utils = "0.4"
netlink-packet-route = "0.6"
netlink-proto = "0.5"
netlink-sys = "0.4"
byteorder = "1"
nftnl = { version = "0.6", features = ["nftnl-1-1-0"] }
mnl = { version = "0.2.0", features = ["mnl-1-0-4"] }
which = { version = "4.0", default-features = false }
tun = { git = "https://github.com/Ch00k/rust-tun.git", branch = "bump-ioctl" }
talpid-dbus = { path = "../talpid-dbus" }


[target.'cfg(target_os = "macos")'.dependencies]
pfctl = { git = "https://github.com/mullvad/pfctl-rs.git" }
system-configuration = "0.4"
tun = { git = "https://github.com/Ch00k/rust-tun.git", branch = "bump-ioctl" }


[target.'cfg(windows)'.dependencies]
widestring = "0.4"
winreg = { version = "0.7", features = ["transactions"] }
winapi = { version = "0.3.6", features = ["combaseapi", "handleapi", "ifdef", "libloaderapi", "netioapi", "stringapiset", "synchapi", "winbase", "winerror", "winuser"] }
socket2 = "0.3"
pnet_packet = "0.26"
talpid-platform-metadata = { path = "../talpid-platform-metadata" }

[build-dependencies]
tonic-build = { version = "0.3", default-features = false, features = ["transport", "prost"] }


[dev-dependencies]
tempfile = "3.0"
quickcheck = "1.0"
quickcheck_macros = "1.0"
