[package]
name = "talpid-core"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>"]
description = "Privacy preserving and secure VPN client library"
license = "GPL-3.0"
edition = "2018"

[dependencies]
atty = "0.2"
derive_more = "0.14"
duct = "0.12"
err-derive = "0.1.5"
futures = "0.1"
jsonrpc-core = { git = "https://github.com/mullvad/jsonrpc", branch = "mullvad-fork" }
jsonrpc-macros = { git = "https://github.com/mullvad/jsonrpc", branch = "mullvad-fork" }
libc = "0.2.20"
log = "0.4"
openvpn-plugin = { git = "https://github.com/mullvad/openvpn-plugin-rs", branch = "auth-failed-event", features = ["serde"] }
os_pipe = "0.8"
parking_lot = "0.7"
regex = "1.1.0"
shell-escape = "0.1"
talpid-ipc = { path = "../talpid-ipc" }
talpid-types = { path = "../talpid-types" }
tokio-core = "0.1"
uuid = { version = "0.7", features = ["v4"] }


[target.'cfg(unix)'.dependencies]
hex = "0.3"
ipnetwork = "0.14"
lazy_static = "1.0"
nix = "0.13"


[target.'cfg(target_os = "linux")'.dependencies]
dbus = "0.6"
failure = "0.1"
netlink-socket = { git = "https://github.com/mullvad/netlink", branch = "ignore-hw-address" }
notify = "4.0"
resolv-conf = "0.6.1"
rtnetlink = { git = "https://github.com/mullvad/netlink", branch = "hack-older-kernel-compat" }
netlink-proto = { git = "https://github.com/mullvad/netlink", branch = "hack-older-kernel-compat" }
netlink-packet = { git = "https://github.com/mullvad/netlink", branch = "hack-older-kernel-compat" }
netlink-sys = { git = "https://github.com/mullvad/netlink", branch = "hack-older-kernel-compat" }
nftnl = { git = "https://github.com/mullvad/nftnl-rs", rev = "29651f4370fdf22cc2e3abf5097a51f8ff17e3a3", features = ["nftnl-1-1-0"] }
mnl = { git = "https://github.com/mullvad/mnl-rs", rev = "f0d19501b9b85be9a1ffaec8317a378bcbdf4fa6", features = ["mnl-1-0-4"] }
which = "2.0"
err-derive = "0.1.5"
tun = "0.4.3"


[target.'cfg(target_os = "macos")'.dependencies]
# TODO: Specify 0.2.1 once the crate gets published
pfctl = { git = "https://github.com/mullvad/pfctl-rs", rev = "9f31b5ddcab941862470075eab83bb398195f3d6" }
system-configuration = "0.2"
tun = "0.4.3"


[target.'cfg(windows)'.dependencies]
widestring = "0.4"
winreg = "0.6"
winapi = { version = "0.3.6", features = ["handleapi", "libloaderapi", "synchapi", "winbase", "winuser"] }


[dev-dependencies]
tempfile = "3.0"
