[package]
name = "talpid-core"
description = "Privacy preserving and secure VPN client library"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
wireguard-go = ["talpid-wireguard/wireguard-go"]
multihop-pcap = ["talpid-wireguard/multihop-pcap"]

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
talpid-channels = { path = "../talpid-channels" }
talpid-dns = { path = "../talpid-dns" }
talpid-firewall = { path = "../talpid-firewall" }
talpid-routing = { path = "../talpid-routing" }
talpid-split-tunnel = { path = "../talpid-split-tunnel" }
talpid-tunnel = { path = "../talpid-tunnel" }
talpid-types = { path = "../talpid-types" }
talpid-wireguard = { path = "../talpid-wireguard" }
tokio = { workspace = true, features = ["process", "rt-multi-thread", "fs"] }

[target.'cfg(target_os = "android")'.dependencies]
jnix = { version = "0.5.1", features = ["derive"] }

[target.'cfg(target_os = "linux")'.dependencies]
nix = { workspace = true }
talpid-dbus = { path = "../talpid-dbus" }

[target.'cfg(target_os = "macos")'.dependencies]
async-trait = "0.1"
hickory-proto = { workspace = true }
hickory-server = { workspace = true, features = ["resolver"] }
nix = { workspace = true, features = ["socket", "signal", "user"] }
serde = { workspace = true, features = ["derive"] }
socket2 = { workspace = true }
talpid-macos = { path = "../talpid-macos" }

[target.'cfg(windows)'.dependencies]
chrono = { workspace = true, features = ["clock"] }
csv = "1.3.1"
winreg = { workspace = true, features = ["transactions"] }
serde = { workspace = true, features = ["derive"] }
parking_lot = "0.12.0"
talpid-windows = { path = "../talpid-windows" }

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Ioctl",
    "Win32_System_IO",
    "Win32_System_LibraryLoader",
    "Win32_System_ProcessStatus",
    "Win32_System_Registry",
    "Win32_System_Rpc",
    "Win32_System_Services",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_SystemInformation",
]

[target.'cfg(target_os = "macos")'.dev-dependencies]
typed-builder = "0.20.0"

[dev-dependencies]
test-log = "0.2.17"
tokio = { workspace = true, features = ["io-util", "test-util", "time"] }
insta = { workspace = true }
