[package]
name = "mullvad-relay-selector"
description = "Mullvad VPN relay selector"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
chrono = { workspace = true }
thiserror = { workspace = true }
ipnetwork = "0.16"
itertools = "0.12"
log = { workspace = true }
once_cell = { workspace = true }
rand = "0.8.5"
serde_json = "1.0"

talpid-types = { path = "../talpid-types" }
mullvad-types = { path = "../mullvad-types" }

[dev-dependencies]
proptest = { workspace = true }
