[package]
name = "mullvad-relay-selector"
description = "Mullvad VPN relay selector"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
chrono = { workspace = true }
err-derive = { workspace = true }
futures = "0.3"
ipnetwork = "0.16"
log = { workspace = true }
parking_lot = "0.12.0"
rand = "0.8.5"
serde_json = "1.0"
tokio = { workspace = true, features =  ["fs", "io-util", "time"] }

talpid-core = { path = "../talpid-core" }
talpid-types = { path = "../talpid-types" }
mullvad-api = { path = "../mullvad-api" }
mullvad-types = { path = "../mullvad-types" }

[dev-dependencies]
once_cell = { workspace = true }
