[package]
name = "mullvad-relay-selector"
version = "0.1.0"
authors = ["Mullvad VPN"]
description = "Mullvad VPN relay selector"
license = "GPL-3.0"
edition = "2021"
publish = false

[dependencies]
chrono = "0.4.19"
err-derive = "0.3.1"
futures = "0.3"
ipnetwork = "0.16"
log = "0.4"
parking_lot = "0.11"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.8", features =  ["fs", "io-util", "time"] }
tokio-stream = "0.1"

talpid-core = { path = "../talpid-core" }
talpid-types = { path = "../talpid-types" }
mullvad-api = { path = "../mullvad-api" }
mullvad-types = { path = "../mullvad-types" }

[dev-dependencies]
lazy_static = "1.0"
