[package]
name = "windows-service"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>", "Andrej Mihajlov <and@mullvad.net>"]

[target.'cfg(windows)'.dependencies]
bitflags = "1.0.1"
error-chain = "0.11"
winapi = { version = "0.3", features = ["std", "winsvc", "winerror"] }
widestring = "0.3.0"

[dev-dependencies]
error-chain = "0.11"
log = "0.4"
simplelog = { version = "0.5", default-features = false }
