[package]
name = "tunnel-obfuscation"
version = "0.1.0"
authors = ["Mullvad VPN"]
description = "Provides different types of obfuscation layers for WireGuard"
license = "GPL-3.0"
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1"
err-derive = "0.3.0"
futures = "0.3.5"
tokio = { version = "1.8", features = ["rt-multi-thread", "macros", "net", "io-util"] }

[dependencies.udp-over-tcp]
git = "https://github.com/mullvad/udp-over-tcp"
rev = "3dae584677ed26aff08ab759f7799a55c0ff1aec"
version = "0.2"
