[package]
name = "talpid-tunnel"
version = "0.0.0"
authors = ["Mullvad VPN"]
description = "Library for creating tunnel devices and interfacing with various VPN tunnels"
license = "GPL-3.0"
edition = "2021"
publish = false

[dependencies]
err-derive = "0.3.1"
cfg-if = "1.0"
ipnetwork = "0.16"
talpid-routing = { path = "../talpid-routing" }
talpid-types = { path = "../talpid-types" }
futures = "0.3.15"
tokio = { version = "1.8", features = ["process", "rt-multi-thread", "fs"] }

[target.'cfg(all(unix, not(target_os = "android")))'.dependencies]
duct = "0.13"
nix = "0.23"

[target.'cfg(target_os = "android")'.dependencies]
jnix = { version = "0.5", features = ["derive"] }
log = "0.4"

[target.'cfg(target_os = "linux")'.dependencies]
tun = "0.5.1"

[target.'cfg(target_os = "macos")'.dependencies]
tun = "0.5.1"

[target.'cfg(windows)'.dependencies]
talpid-windows-net = { path = "../talpid-windows-net" }

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.42.0"
features = [
    "Win32_Foundation",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_Ndis",
]
