[package]
name = "talpid-tunnel"
description = "Library for creating tunnel devices and interfacing with various VPN tunnels"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
cfg-if = "1.0"
ipnetwork = "0.16"
talpid-routing = { path = "../talpid-routing" }
talpid-types = { path = "../talpid-types" }
futures = "0.3.15"
tokio = { workspace = true, features = ["process", "rt-multi-thread", "fs"] }

[target.'cfg(all(unix, not(target_os = "android")))'.dependencies]
duct = "0.13"
nix = "0.23"

[target.'cfg(target_os = "android")'.dependencies]
jnix = { version = "0.5.1", features = ["derive"] }
log = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
tun = "0.5.1"

[target.'cfg(target_os = "macos")'.dependencies]
tun = "0.5.1"

[target.'cfg(windows)'.dependencies]
talpid-windows = { path = "../talpid-windows" }

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_Ndis",
]
