[package]
name = "talpid-tunnel"
edition.workspace = true
rust-version.workspace = true
description = "Library for creating tunnel devices and interfacing with various VPN tunnels"
repository.workspace = true
license.workspace = true

[dependencies]
cfg-if = "1.0"
futures = { workspace = true }
ipnetwork = { workspace = true }
talpid-routing = { path = "../talpid-routing" }
talpid-types = { path = "../talpid-types" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "process", "rt-multi-thread"] }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
tun = { workspace = true, optional = true }  # use tun 0.5.5 for wireguard-go

[target.'cfg(not(target_os = "android"))'.dependencies]
tun08 = { workspace = true, features = ["async"] }

[target.'cfg(target_os = "android")'.dependencies]
jnix = { version = "0.5.1", features = ["derive"] }
log = { workspace = true }

[target.'cfg(windows)'.dependencies]
talpid-windows = { path = "../talpid-windows" }

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
  "Win32_Foundation",
  "Win32_NetworkManagement_Ndis",
  "Win32_Networking_WinSock",
]

[features]
wireguard-go = ["dep:tun"]

[lints]
workspace = true
