[package]
name = "shadowsocks-proxy"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
crate-type = [ "rlib", "staticlib" ]
bench = false

[dependencies]
shadowsocks-service = { workspace = true, features = [ "local", "stream-cipher", "local-http", "local-tunnel" ] }

tokio = { workspace = true }
log = "0.4"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
oslog = "0.2"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.build-dependencies]
cbindgen = { version = "0.24.3", default-features = false }
