[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

[target.x86_64-unknown-linux-gnu.mnl]
rustc-link-lib = ["mnl"]
rustc-link-search = ["native=dist-assets/binaries/x86_64-unknown-linux-gnu"]
[target.aarch64-unknown-linux-gnu.mnl]
rustc-link-lib = ["mnl"]
rustc-link-search = ["native=dist-assets/binaries/aarch64-unknown-linux-gnu"]
[target.x86_64-unknown-linux-gnu.nftnl]
rustc-link-lib = ["nftnl", "mnl"]
rustc-link-search = ["native=dist-assets/binaries/x86_64-unknown-linux-gnu"]
[target.aarch64-unknown-linux-gnu.nftnl]
rustc-link-lib = ["nftnl", "mnl"]
rustc-link-search = ["native=dist-assets/binaries/aarch64-unknown-linux-gnu"]
