[package]
name = "mullvad-version"
version = "0.0.0"
authors = ["Mullvad VPN"]
license = "GPL-3.0"
edition = "2021"
publish = false

description = """
Computes the Mullvad VPN app product version. This crate is the single source of truth for
what version string a build should have. This crate is responsible for computing the
`-dev-$git_hash` suffix as well as transforming the version into semver, Android versionCode
and other formats.
"""

[target.'cfg(not(target_os="android"))'.dependencies]
regex = "1.6.0"
