[package]
name = "mullvad-cli"
version = "2020.1.0-beta1"
authors = ["Mullvad VPN"]
description = "Manage the Mullvad VPN daemon via a convenient CLI"
license = "GPL-3.0"
edition = "2018"
publish = false

[[bin]]
name = "mullvad"
path = "src/main.rs"

[dependencies]
base64 = "0.10"
chrono = { version = "0.4", features = ["serde"] }
clap = "2.32"
err-derive = "0.2.1"
env_logger = "0.7"
futures = "0.1"
natord = "1.0.9"
serde = "1.0"

mullvad-ipc-client = { path = "../mullvad-ipc-client" }
mullvad-types = { path = "../mullvad-types" }
mullvad-paths = { path = "../mullvad-paths" }
talpid-types = { path = "../talpid-types" }
talpid-ipc = { path = "../talpid-ipc" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
winapi = "0.3"

[package.metadata.winres]
ProductName = "Mullvad VPN"
CompanyName = "Amagicom AB"
LegalCopyright = "(c) 2020 Amagicom AB"
InternalName = "mullvad-cli"
OriginalFilename = "mullvad.exe"
