[package]
name = "mullvad-cli"
version = "2019.7.0"
authors = [
    "Mullvad VPN <admin@mullvad.net>",
    "Andrej Mihajlov <and@mullvad.net>",
    "Emīls Piņķis <emils@mullvad.net>",
    "Erik Larkö <erik@mullvad.net>",
    "Janito Vaqueiro Ferreira Filho <janito@mullvad.net>",
    "Linus Färnstrand <linus@mullvad.net>",
]
description = "Manage the Mullvad VPN daemon via a convenient CLI"
license = "GPL-3.0"
edition = "2018"

[[bin]]
name = "mullvad"
path = "src/main.rs"

[dependencies]
clap = "2.32"
err-derive = "0.1.5"
env_logger = "0.6"
serde = "1.0"
futures = "0.1"
base64 = "0.10"
chrono = { version = "0.4", features = ["serde"] }

mullvad-ipc-client = { path = "../mullvad-ipc-client" }
mullvad-types = { path = "../mullvad-types" }
mullvad-paths = { path = "../mullvad-paths" }
talpid-types = { path = "../talpid-types" }
talpid-ipc = { path = "../talpid-ipc" }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
winapi = "0.3"

[package.metadata.winres]
ProductName = "Mullvad VPN"
CompanyName = "Amagicom AB"
LegalCopyright = "(c) 2018 Amagicom AB"
InternalName = "mullvad-cli"
OriginalFilename = "mullvad.exe"
