[package]
name = "mullvad-cli"
version = "2021.1.0"
authors = ["Mullvad VPN"]
description = "Manage the Mullvad VPN daemon via a convenient CLI"
license = "GPL-3.0"
edition = "2018"
publish = false

[[bin]]
name = "mullvad"
path = "src/main.rs"

[dependencies]
base64 = "0.13"
chrono = { version = "0.4", features = ["serde"] }
clap = "2.32"
err-derive = "0.3.0"
env_logger = "0.8.2"
futures = "0.3"
natord = "1.0.9"
serde = "1.0"
itertools = "0.10"

mullvad-types = { path = "../mullvad-types" }
mullvad-paths = { path = "../mullvad-paths" }
talpid-types = { path = "../talpid-types" }

mullvad-management-interface = { path = "../mullvad-management-interface" }
tokio = { version = "0.2", features =  [ "rt-threaded" ] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
winapi = "0.3"

[package.metadata.winres]
ProductName = "Mullvad VPN"
CompanyName = "Mullvad VPN AB"
LegalCopyright = "(c) 2021 Mullvad VPN AB"
InternalName = "mullvad-cli"
OriginalFilename = "mullvad.exe"
