[package]
name = "mullvad-cli"
version = "2020.5.0"
authors = ["Mullvad VPN"]
description = "Manage the Mullvad VPN daemon via a convenient CLI"
license = "GPL-3.0"
edition = "2018"
publish = false

[features]
default = []
shell-completions = []

[[bin]]
name = "mullvad"
path = "src/main.rs"

[dependencies]
async-trait = "0.1"
base64 = "0.10"
chrono = { version = "0.4", features = ["serde"] }
clap = "2.32"
err-derive = "0.2.1"
env_logger = "0.7"
futures = "0.1"
natord = "1.0.9"
serde = "1.0"

mullvad-types = { path = "../mullvad-types" }
mullvad-paths = { path = "../mullvad-paths" }
talpid-types = { path = "../talpid-types" }

tonic = "0.2"
tower = "0.3"
prost = "0.6"
prost-types = "0.6"
futures03 = { package = "futures", version = "0.3", features = [ "compat" ]}
tokio = { version = "0.2", features =  [ "io-util", "process", "rt-core", "rt-threaded", "stream"] }

parity-tokio-ipc = "0.7"

[build-dependencies]
tonic-build = { version = "0.2", default-features = false, features = ["transport", "prost"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
winapi = "0.3"

[package.metadata.winres]
ProductName = "Mullvad VPN"
CompanyName = "Mullvad VPN AB"
LegalCopyright = "(c) 2020 Mullvad VPN AB"
InternalName = "mullvad-cli"
OriginalFilename = "mullvad.exe"
