[package]
name = "raas"
version = "0.1.0"
edition = "2021"
description = "RaaS stands for Router as a Service"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nftnl = { version = "0.7", features = ["nftnl-1-1-0"] }
mnl = { version = "0.2", features = ["mnl-1-0-4"] }
once_cell = "1"
log = "0.4"
env_logger = "0.10"

axum = "0.7"
pnet_packet = "0.34"
pcap = { version = "1.2.0", features = ["capture-stream"] }
pcap-file-tokio = "0.1"
thiserror = "1"
tower = "0.4"
tower-http = { version = "0.5", features = [ "trace" ] }
tokio = { version = "1.0", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
futures = "0.3"
tracing = "0.1.35"
tracing-subscriber = "0.3.14"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1", features = [ "serde" ] }
anyhow = "1"

