[package]
name = "raas"
version = "0.1.0"
edition = "2021"
description = "RaaS stands for Router as a Service"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
axum = "0.7"
env_logger = "0.10"
futures = "0.3"
ipnetwork = { version = "0.21", features = ["serde"] }
log = "0.4"
mnl = { version = "0.2", features = ["mnl-1-0-4"] }
nftnl = { version = "0.9", features = ["nftnl-1-1-0"] }
once_cell = "1"
pcap = { version = "1.2.0", features = ["capture-stream"] }
pcap-file-tokio = "0.1"
pnet_packet = "0.34"
serde = { version = "1.0.138", features = ["derive"] }
thiserror = "1"
tokio = { version = "1.0", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["trace"] }
uuid = { version = "1", features = ["serde"] }
