[package]
name = "talpid-ipc"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>", "Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>", "Andrej Mihajlov <and@mullvad.net>"]
description = "IPC client and server for talpid"
license = "GPL-3.0"

[dependencies]
error-chain = "0.12"
serde = "1.0"
serde_json = "1.0"
log = "0.4"
jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc", tag = "v8.0.1" }
jsonrpc-pubsub = { git = "https://github.com/paritytech/jsonrpc", tag = "v8.0.1" }
jsonrpc-ws-server = { git = "https://github.com/paritytech/jsonrpc", tag = "v8.0.1" }
ws = { git = "https://github.com/tomusdrw/ws-rs" }
url = "1.4"

[dev-dependencies]
assert_matches = "1.0"
env_logger = "0.5"
jsonrpc-macros = { git = "https://github.com/paritytech/jsonrpc", tag = "v8.0.1" }
