[package]
name = "mullvad-setup"
version = "2022.5.0-beta2"
authors = ["Mullvad VPN"]
description = "Tool used to manage daemon setup"
license = "GPL-3.0"
edition = "2021"
publish = false

[[bin]]
name = "mullvad-setup"
path = "src/main.rs"

[dependencies]
clap = { version = "3.0", features = ["cargo"] }
env_logger = "0.8.2"
err-derive = "0.3.1"
lazy_static = "1.1.0"

mullvad-management-interface = { path = "../mullvad-management-interface" }

tokio = { version = "1.8", features =  ["rt-multi-thread"] }

mullvad-daemon = { path = "../mullvad-daemon" }
mullvad-paths = { path = "../mullvad-paths" }
mullvad-api = { path = "../mullvad-api" }
mullvad-types = { path = "../mullvad-types" }
talpid-core = { path = "../talpid-core" }
talpid-types = { path = "../talpid-types" }

[target.'cfg(windows)'.dependencies]
widestring = "0.5"

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.42.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Com",
    "Win32_System_ProcessStatus",
    "Win32_System_Threading",
    "Win32_UI_Shell",
]
