[package]
name = "mullvad-setup"
version = "2021.6.0"
authors = ["Mullvad VPN"]
description = "Tool used to manage daemon setup"
license = "GPL-3.0"
edition = "2021"
publish = false

[[bin]]
name = "mullvad-setup"
path = "src/main.rs"

[dependencies]
clap = "2.32"
env_logger = "0.8.2"
err-derive = "0.3.0"
lazy_static = "1.1.0"

mullvad-management-interface = { path = "../mullvad-management-interface" }

tokio = { version = "1.8", features =  [ "rt-multi-thread" ] }

mullvad-daemon = { path = "../mullvad-daemon" }
mullvad-paths = { path = "../mullvad-paths" }
mullvad-rpc = { path = "../mullvad-rpc" }
mullvad-types = { path = "../mullvad-types" }
talpid-core = { path = "../talpid-core" }
talpid-types = { path = "../talpid-types" }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.6", features = [ "securitybaseapi", "impl-default", "impl-debug", "handleapi", "psapi" ]}
widestring = "0.5"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
winapi = "0.3"

[package.metadata.winres]
ProductName = "Mullvad VPN"
CompanyName = "Mullvad VPN AB"
LegalCopyright = "(c) 2021 Mullvad VPN AB"
InternalName = "mullvad-setup"
OriginalFilename = "mullvad-setup.exe"
