[package]
name = "mullvad-jni"
description = "JNI interface for the Mullvad daemon"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true

[features]
# Allow the API server to use to be configured
api-override = ["mullvad-api/api-override"]

[lib]
crate_type = ["cdylib"]

[target.'cfg(target_os = "android")'.dependencies]
err-derive = "0.3.1"
futures = "0.3"
ipnetwork = "0.16"
jnix = { version = "0.5", features = ["derive"] }
lazy_static = "1"
log = "0.4"
log-panics = "2"
nix = "0.23"
rand = "0.8.5"
tokio = { workspace = true }

mullvad-daemon = { path = "../mullvad-daemon" }
mullvad-paths = { path = "../mullvad-paths" }
mullvad-problem-report = { path = "../mullvad-problem-report" }
mullvad-types = { path = "../mullvad-types" }
mullvad-api = { path = "../mullvad-api" }
talpid-core = { path = "../talpid-core" }
talpid-tunnel = { path = "../talpid-tunnel" }
talpid-types = { path = "../talpid-types" }
