[package]
name = "mullvad-jni"
version = "0.1.0"
authors = ["Mullvad VPN"]
description = "JNI interface for the Mullvad daemon"
license = "GPL-3.0"
edition = "2018"
publish = false

[lib]
crate_type = ["cdylib"]

[target.'cfg(target_os = "android")'.dependencies]
err-derive = "0.2.1"
futures = "0.1"
ipnetwork = "0.15"
jnix = { version = "0.2.2", features = ["derive"] }
jsonrpc-client-core = "0.5"
jsonrpc-core = "8"
lazy_static = "1"
log = "0.4"
log-panics = "2"

mullvad-daemon = { path = "../mullvad-daemon" }
mullvad-paths = { path = "../mullvad-paths" }
mullvad-problem-report = { path = "../mullvad-problem-report" }
mullvad-types = { path = "../mullvad-types" }
talpid-core = { path = "../talpid-core" }
talpid-types = { path = "../talpid-types" }
