[package]
name = "mullvad-jni"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>"]
description = "JNI interface for the Mullvad daemon"
license = "GPL-3.0"
edition = "2018"

[lib]
crate_type = ["cdylib"]

[dependencies]
err-derive = "0.1.5"
futures = "0.1"
ipnetwork = "0.15"
jni = "0.12"
jsonrpc-client-core = "0.5"
lazy_static = "1"
libc = "0.2"
log = "0.4"
log-panics = "2"
parking_lot = "0.9"

mullvad-daemon = { path = "../mullvad-daemon" }
mullvad-paths = { path = "../mullvad-paths" }
mullvad-problem-report = { path = "../mullvad-problem-report" }
mullvad-types = { path = "../mullvad-types" }
talpid-core = { path = "../talpid-core" }
talpid-types = { path = "../talpid-types" }
