[package]
name = "talpid-windows"
edition.workspace = true
rust-version.workspace = true
description = "Nice abstractions for Windows"
repository.workspace = true
license.workspace = true

[target.'cfg(windows)'.dependencies]
futures = { workspace = true }
socket2 = { workspace = true }
talpid-types = { path = "../talpid-types" }
thiserror = { workspace = true }

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
  "Win32_Foundation",
  "Win32_Globalization",
  "Win32_NetworkManagement_IpHelper",
  "Win32_NetworkManagement_Ndis",
  "Win32_Networking_WinSock",
  "Win32_Security",
  "Win32_Security_Authorization",
  "Win32_System_Diagnostics_ToolHelp",
  "Win32_System_IO",
  "Win32_System_SystemInformation",
  "Win32_System_Threading",
]

[target.'cfg(windows)'.dev-dependencies.windows-sys]
workspace = true
features = ["Win32_Storage", "Win32_Storage_FileSystem"]

[lints]
workspace = true
