[package]
name = "talpid-windows"
description = "Nice abstractions for Windows"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[target.'cfg(windows)'.dependencies]
thiserror = { workspace = true }
socket2 = { version = "0.5.3" }
futures = "0.3.15"

talpid-types = { path = "../talpid-types" }

[target.'cfg(windows)'.dependencies.windows-sys]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_IO",
    "Win32_Networking_WinSock",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
]
