[package]
name = "talpid-openvpn-plugin"
version = "2022.3.0-beta1"
authors = ["Mullvad VPN"]
description = "OpenVPN shared library plugin for relaying OpenVPN events to talpid_core"
license = "GPL-3.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
err-derive = "0.3.1"
log = "0.4"
env_logger = "0.8.2"
parity-tokio-ipc = "0.9"
tokio = { version = "1.8", features =  ["rt"] }

openvpn-plugin = { version = "0.4", features = ["serde", "log", "auth-failed-event"] }
talpid-types = { path = "../talpid-types" }

tonic = "0.5"
tower = "0.4"
prost = "0.8"

[build-dependencies]
tonic-build = { version = "0.5", default-features = false, features = ["transport", "prost"] }


[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
winapi = "0.3"

[package.metadata.winres]
ProductName = "Mullvad VPN"
CompanyName = "Mullvad VPN AB"
LegalCopyright = "(c) 2022 Mullvad VPN AB"
InternalName = "talpid-openvpn-plugin"
OriginalFilename = "talpid_openvpn_plugin.dll"
