[package]
name = "talpid-openvpn-plugin"
version = "2020.7.0-beta2"
authors = ["Mullvad VPN"]
description = "OpenVPN shared library plugin for relaying OpenVPN events to talpid_core"
license = "GPL-3.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
err-derive = "0.2.1"
log = "0.4"
env_logger = "0.7"
parity-tokio-ipc = "0.7"
tokio = { package = "tokio", version = "0.2", features =  [ "rt-core", "rt-threaded"] }

openvpn-plugin = { git = "https://github.com/mullvad/openvpn-plugin-rs", branch = "auth-failed-event", features = ["serde", "log"] }
talpid-types = { path = "../talpid-types" }

tonic = "0.3.1"
tower = "0.3"
prost = "0.6"

[build-dependencies]
tonic-build = { version = "0.3", default-features = false, features = ["transport", "prost"] }


[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
winapi = "0.3"

[package.metadata.winres]
ProductName = "Mullvad VPN"
CompanyName = "Mullvad VPN AB"
LegalCopyright = "(c) 2020 Mullvad VPN AB"
InternalName = "talpid-openvpn-plugin"
OriginalFilename = "talpid_openvpn_plugin.dll"
