[package]
name = "talpid-tunnel-config-client-proxy"
description = "Uses the relay RPC service to set up PQ-safe peers, etc."
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
talpid-tunnel-config-client = { path = "../../../talpid-tunnel-config-client" }
talpid-types = { path = "../../../talpid-types" }

log = { workspace = true }
rand = "0.8"
tonic = { workspace = true }
futures = "0.3"
tower = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
classic-mceliece-rust = { version = "2.0.0", features = [
    "mceliece460896f",
    "zeroize",
] }
pqc_kyber = { version = "0.4.0", features = ["std", "kyber1024", "zeroize"] }
zeroize = "1.5.7"
libc = "0.2"

[lib]
crate-type = ["rlib", "staticlib"]
bench = false

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread"] }
[build-dependencies]
tonic-build = { workspace = true, default-features = false, features = [
    "transport",
    "prost",
] }
cbindgen = { version = "0.24.3", default-features = false }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
oslog = "0.2"
