---
name: Android - Check XML formatting
on:
  pull_request:
    paths:
      - .github/workflows/android-xml-tidy.yml
      - android/app/src/main/**/*.xml
  workflow_dispatch:
jobs:
  xml-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |-
          sudo apt-get install tidy
          source android/scripts/ci-android-xml.sh
          tidy-verify-xml
