---
name: Desktop check gRPC bindings
on:
  pull_request:
    paths:
      - .github/workflows/desktop-grpc-bindings.yml
      - desktop/packages/management-interface/dist/**
      - mullvad-management-interface/proto/**
  workflow_dispatch:

permissions: {}

jobs:
  check-grpc-bindings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/mullvad-build-env

      - name: Generate bindings
        working-directory: desktop
        run: npm run build -w management-interface

      - name: Check working directory is clean
        run: git diff --exit-code HEAD
