---
name: iOS end-to-end nightly tests
on:
  workflow_dispatch:
  schedule:
    # At midnight every day.
    # Notifications for scheduled workflows are sent to the user who last modified the cron
    # syntax in the workflow file. If you update this you must have notifications for
    # Github Actions enabled, so these don't go unnoticed.
    # https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs
    - cron: '0 0 * * *'

permissions: {}

jobs:
  reuse-e2e-workflow:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: ./.github/workflows/ios-end-to-end-tests.yml
    with:
      arg_tests_json_key: "nightly"
    secrets: inherit

  notify-on-failure:
    if: failure()
    name: Notify team on nightly E2E failure
    runs-on: [self-hosted, macOS, ios-test]
    needs: reuse-e2e-workflow
    timeout-minutes: 5
    steps:
      - name: Send custom event details to a Slack workflow
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.IOS_SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            run_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
