---
name: Rust - Check formatting
on:
  pull_request:
    paths:
      - .github/workflows/rustfmt.yml
      - rustfmt.toml
      - '**/*.rs'
  workflow_dispatch:

permissions: {}

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/mullvad-build-env
        with:
          rustup-components: rustfmt

      - name: Check formatting
        run: |-
          rustfmt --version
          cargo fmt -- --check

  check-formatting-raas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/mullvad-build-env
        with:
          rustup-components: rustfmt

      - name: Check formatting
        run: |-
          cd ci/ios/test-router/raas && rustfmt --version
          cd ci/ios/test-router/raas && cargo fmt -- --check
