[package]
name = "talpid-time"
edition.workspace = true
rust-version.workspace = true
description = "Time functions"
repository.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true, features = ["time"] }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["time"] }

[features]
# This feature should only be enabled for testing (in dev-dependencies). When enabled, timers will
# use the standard tokio `Instant`, making it possible to advance/pause timers as expected in tests.
test = []

[lints]
workspace = true
