[package]
name = "mullvad-problem-report"
version = "2020.6.0"
authors = ["Mullvad VPN"]
description = "Collect Mullvad VPN logs into a report and send it to support"
license = "GPL-3.0"
edition = "2018"
publish = false

[dependencies]
clap = "2.25"
dirs = "3.0"
env_logger = "0.7"
err-derive = "0.2.1"
lazy_static = "1.0"
regex = "1.0"
uuid = { version = "0.8", features = ["v4"] }
tokio = { version = "0.2", features = [ "rt-core" ] }

mullvad-paths = { path = "../mullvad-paths" }
mullvad-rpc = { path = "../mullvad-rpc" }
talpid-types = { path = "../talpid-types" }


[target.'cfg(target_os = "android")'.dependencies]
duct = "0.13"


[target.'cfg(target_os = "linux")'.dependencies]
rs-release = "0.1.7"


[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
winapi = "0.3"


[package.metadata.winres]
ProductName = "Mullvad VPN"
CompanyName = "Mullvad VPN AB"
LegalCopyright = "(c) 2020 Mullvad VPN AB"
InternalName = "mullvad-problem-report"
OriginalFilename = "mullvad-problem-report.exe"
