[package]
name = "mullvad-problem-report"
version = "2021.3.0-beta2"
authors = ["Mullvad VPN"]
description = "Collect Mullvad VPN logs into a report and send it to support"
license = "GPL-3.0"
edition = "2018"
publish = false

[dependencies]
clap = "2.25"
dirs-next = "2.0"
env_logger = "0.8.2"
err-derive = "0.3.0"
lazy_static = "1.0"
regex = "1.0"
uuid = { version = "0.8", features = ["v4"] }
tokio = { version = "0.2", features = [ "rt-core" ] }

mullvad-paths = { path = "../mullvad-paths" }
mullvad-rpc = { path = "../mullvad-rpc" }
talpid-types = { path = "../talpid-types" }
talpid-platform-metadata = { path = "../talpid-platform-metadata" }


[target.'cfg(target_os = "android")'.dependencies]
duct = "0.13"


[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
winapi = "0.3"


[package.metadata.winres]
ProductName = "Mullvad VPN"
CompanyName = "Mullvad VPN AB"
LegalCopyright = "(c) 2021 Mullvad VPN AB"
InternalName = "mullvad-problem-report"
OriginalFilename = "mullvad-problem-report.exe"
