[package]
name = "mullvad-problem-report"
version = "2019.8.0"
authors = [
    "Mullvad VPN <admin@mullvad.net>",
    "Andrej Mihajlov <and@mullvad.net>",
    "Emīls Piņķis <emils@mullvad.net>",
    "Erik Larkö <erik@mullvad.net>",
    "Janito Vaqueiro Ferreira Filho <janito@mullvad.net>",
    "Linus Färnstrand <linus@mullvad.net>",
]
description = "Collect Mullvad VPN logs into a report and send it to support"
license = "GPL-3.0"
edition = "2018"

[[bin]]
name = "problem-report"
path = "src/main.rs"

[dependencies]
clap = "2.25"
dirs = "1.0"
env_logger = "0.6"
err-derive = "0.1.5"
lazy_static = "1.0"
regex = "1.0"
tokio-core = "0.1"
uuid = { version = "0.7", features = ["v4"] }

mullvad-paths = { path = "../mullvad-paths" }
mullvad-rpc = { path = "../mullvad-rpc" }
talpid-types = { path = "../talpid-types" }


[target.'cfg(target_os = "android")'.dependencies]
duct = "0.12"


[target.'cfg(target_os = "linux")'.dependencies]
rs-release = { git = "https://github.com/mullvad/rs-release", branch = "snailquote-unescape" }


[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
winapi = "0.3"


[package.metadata.winres]
ProductName = "Mullvad VPN"
CompanyName = "Amagicom AB"
LegalCopyright = "(c) 2018 Amagicom AB"
InternalName = "mullvad-problem-report"
OriginalFilename = "problem-report.exe"
