[package]
name = "mullvad-problem-report"
version = "2018.2.0"
authors = ["Mullvad VPN <admin@mullvad.net>", "Linus FÃ¤rnstrand <linus@mullvad.net>", "Andrej Mihajlov <and@mullvad.net>"]
description = "Collect Mullvad VPN logs into a report and send it to support"
license = "GPL-3.0"

[[bin]]
name = "problem-report"
path = "src/main.rs"

[dependencies]
clap = "2.25"
dirs = "1.0"
error-chain = "0.12"
lazy_static = "1.0"
regex = "1.0"
uuid = { version = "0.6", features = ["v4"] }

mullvad-paths = { path = "../mullvad-paths" }
mullvad-rpc = { path = "../mullvad-rpc" }

[target.'cfg(target_os = "linux")'.dependencies]
rs-release = { git = "https://github.com/mullvad/rs-release", branch = "snailquote-unescape" }

[target.'cfg(windows)'.build-dependencies]
windres = "0.1"
