# See repository root `osv-scanner.toml` for instructions and rules for this file.

# yargs-parser Vulnerable to Prototype Pollution
[[IgnoredVulns]]
id = "CVE-2020-7608" # GHSA-p9pc-299p-vxgp
ignoreUntil = 2024-12-05
reason = "This package is only used to parse commands run by either us or trusted libraries"

# PostCSS line return parsing error
[[IgnoredVulns]]
id = "CVE-2023-44270" # GHSA-7fh5-64p2-3v2j
ignoreUntil = 2025-03-05
reason = "This project does not use PostCSS to parse untrusted CSS"

# braces: Uncontrolled resource consumption
[[IgnoredVulns]]
id = "CVE-2024-4068" # GHSA-grv7-fg5c-xmjg
ignoreUntil = 2025-03-05
reason = "This package is only used to match paths from either us or trusted libraries"

# micromatch (dev): Regular Expression Denial of Service (ReDoS) in micromatch
[[IgnoredVulns]]
id = "CVE-2024-4067" # GHSA-952p-6rrq-rcjv
ignoreUntil = 2025-02-23
reason = "This is just a dev dependency, and we don't have untrusted input to micromatch there"

# node-gettext: Prototype Pullution via the addTranslations function
[[IgnoredVulns]]
id = "CVE-2024-21528" # GHSA-g974-hxvm-x689
ignoreUntil = 2025-01-17
reason = "There is no fix yet and we don't send untrusted input to the first argument of addTranslations"
