# See repository root `osv-scanner.toml` for instructions and rules for this file.

# node-gettext: Prototype Pullution via the addTranslations function
[[IgnoredVulns]]
id = "CVE-2024-21528"  # GHSA-g974-hxvm-x689
ignoreUntil = 2026-04-16  # The vulnerability is ignored for 6 months as the affected library is not receiving updates and we can not patch the vulnerability without migrating to another library, which is no minor feat.
reason = "There is no fix yet and we don't send untrusted input to the first argument of addTranslations"

# tar: node-tar is Vulnerable to Arbitrary File Overwrite and Symlink Poisoning via Insufficient Path Sanitization
[[IgnoredVulns]]
id = "CVE-2026-23745"  # GHSA-8qq5-rm4j-mr97
ignoreUntil = 2026-03-02
reason = "The vulnerable tar dependency does not handle arbitrary tar files as it is only used by grpc-tools. Unless the files uploaded by the grpc-tools team to node-precompiled-binaries.grpc.io are compromised an attack is not possible."

# tar: Race Condition in node-tar Path Reservations via Unicode Ligature Collisions on macOS APFS
[[IgnoredVulns]]
id = "CVE-2026-23950"  # GHSA-r6q2-hw4h-h46w
ignoreUntil = 2026-03-02
reason = "The vulnerable tar dependency does not handle arbitrary tar files as it is only used by grpc-tools. Unless the files uploaded by the grpc-tools team to node-precompiled-binaries.grpc.io are compromised an attack is not possible."

# tar: node-tar Vulnerable to Arbitrary File Creation/Overwrite via Hardlink Path Traversal
[[IgnoredVulns]]
id = "CVE-2026-24842"  # GHSA-34x7-hfp2-rc4v
ignoreUntil = 2026-03-02
reason = "The vulnerable tar dependency does not handle arbitrary tar files as it is only used by grpc-tools. Unless the files uploaded by the grpc-tools team to node-precompiled-binaries.grpc.io are compromised an attack is not possible."

# ajv: ajv has ReDoS when using $data option
[[IgnoredVulns]]
id = "CVE-2025-69873"  # GHSA-2g4f-4pwh-qvx6
ignoreUntil = 2026-08-04
reason = "This vulnerability only concerns ReDoS and the package is only used in development by eslint and electron-builder. eslint explicitly does not use the $data option and electron-builder uses it to validate its config, which we fully dictate ourselves."

# tar: Arbitrary File Read/Write via Hardlink Target Escape Through Symlink Chain in node-tar Extraction
[[IgnoredVulns]]
id = "CVE-2026-26960"  # GHSA-83g3-92jg-28cx
ignoreUntil = 2026-03-02
reason = "The vulnerable tar dependency does not handle arbitrary tar files as it is only used by grpc-tools. Unless the files uploaded by the grpc-tools team to node-precompiled-binaries.grpc.io are compromised an attack is not possible."
